CarShop/Models/Entityes/Cart.cs
namespace CarShop.Models.Entityes
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();
        public IEnumerable<CartLine> Lines
        {
            get { return lineCollection; }
        }

        public void AddItem(Product product, int quantity)
        {
            CartLine? line = lineCollection.Where(p => p.Product.Id == product.Id).FirstOrDefault();

            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public void RemoveLine(Product product)
        {
            lineCollection.RemoveAll(l => l.Product.Id == product.Id);
        }

        public decimal ComputeTotalValue()
        {
            return lineCollection.Sum(e => e.Product.Price * e.Quantity);
        }

        public void Clear()
        {
            lineCollection.Clear();
        }
    }
}

CarShop/Controllers/CaarsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using CarShop.Models.Entityes;
using Microsoft.AspNetCore.Authorization;
using Duende.IdentityServer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.VisualBasic;

namespace CarShop.Controllers
{
    [Authorize]
    public class CaarsController : Controller
    {
        private HttpClient _httpClient;
        public CaarsController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
        }

        [HttpGet]
        [Route("Catalog")]
        public async Task<IActionResult> CatalogAsync()
        {
            var response = await _httpClient.GetAsync("http://localhost:5193/Product");
            response.EnsureSuccessStatusCode();
            var model = await response.Content.ReadAsAsync<List<Product>>();
            return View(model);
        }

        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }

        /*
        [HttpPost]
        public IActionResult GreateTest(CarViewModel ca)
        {
            if (ModelState.IsValid)
            {
                _iCarSevises.Create(ca);
                List<CarViewModel> model = _iCarSevises.GetAll();

                return View("~/Views/Caars/Test.cshtml", model);
            }
            string errorMessages = "";
            // проходим по всем элементам в ModelState
            foreach (var item in ModelState)
            {
                // если для определенного элемента имеются ошибки
                if (item.Value.ValidationState == ModelValidationState.Invalid)
                {
                    errorMessages = $"{errorMessages}\nОшибки для свойства {item.Key}:\n";
                    // пробегаемся по всем ошибкам
                    foreach (var error in item.Value.Errors)
                    {
                        errorMessages = $"{errorMessages}{error.ErrorMessage}\n";
                    }
                }
            }
            return View(errorMessages);
        }

        [HttpPost]
        [Route("DeleteTest")]
        [CustomExceptionFilter]
        public IActionResult DeleteTest(int id)
        {
            if (id == 1 || id == 2)
                throw new Exception();
            _iCarSevises.Delete(id);
            return RedirectToAction("Test");
        }
        */

        [HttpGet]
        [Route("Info")]
        public async Task<IActionResult> InfoAsync(int id)
        {
            var response = await _httpClient.GetAsync($"http://localhost:5193/Product/{id}");
            response.EnsureSuccessStatusCode();
            var model = await response.Content.ReadAsAsync<Product>();
            return View(model);
        }

        /*
        [HttpPost]
        [Route("UpdateTest")]
        public IActionResult UpdateTest(CarViewModel ca)
        {

            _iCarSevises.Update(ca);
            List<CarViewModel> model = _iCarSevises.GetAll();
            return View("~/Views/Caars/Test.cshtml", model);
        }
*/
    }
}

CarShop/Controllers/OrderController.cs
using CarShop.Models.Entityes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Web;
using Microsoft.AspNetCore.Session;
using System;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using System.Text.Json.Nodes;

namespace CarShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private HttpClient _httpClient;
        public OrderController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
        }

        [HttpGet]
        public async Task<IActionResult> MyOrdersAsync()
        {
            var response = await _httpClient.GetAsync("http://localhost:5247/Order");
            response.EnsureSuccessStatusCode();
            var order = await response.Content.ReadAsAsync<List<Order>>();
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> SaveOrderAsync(Order order)
        {
            if (ModelState.IsValid)
            {
                var cart = GetCart();
                order.IdProducts = cart.Lines.Select(x=>x.Product.Id).ToList();
                order.Created = DateTime.Now;
                var jsonObject = JsonConvert.SerializeObject(order);
                var content = new StringContent(jsonObject.ToString(), Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("http://localhost:5247/Order", content);
                var contents = await response.Content.ReadAsStringAsync();
                return View("SaveOrder");
            }
            else
            {
                return View("NotSaveOrder");
            }
        }

        private Cart GetCart()
        {
            var cartstring = HttpContext.Session.GetString("Cart");
            if (string.IsNullOrEmpty(cartstring))
            {
                return new Cart();
            }

            var cart = JsonConvert.DeserializeObject<Cart>(HttpContext.Session.GetString("Cart"));
            return cart;
        }
    }
}

CarShop/Views/Cart/MyCart.cshtml
@model CarShop.Models.Entityes.CartIndexViewModel
@{
  ViewBag.Title = "Sports Store: Your Cart";
}
<h2>Your cart</h2>
<div>
<table width="90%" align="center">
  <thead>
    <tr>
      <th align="left">Quantity</th>
      <th align="left">Item</th>
      <th align="left">Price</th>
      <th align="left">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var line in Model.Cart.Lines) {
      <tr>
        <td align="left">@line.Quantity</td>
        <td align="left">@line.Product.Name</td>
        <td align="left">@line.Product.Price.ToString("N2") $</td>
        <td align="left">@((line.Quantity * line.Product.Price).ToString("N2")) $</td>
        <td align="center">@using (Html.BeginForm("RemoveFromCart", "Cart", FormMethod.Get))
               {
                   <input type="hidden" name="id" value="@line.Product.Id"/>
                 <span>  <button  type="submit">X</button></span>
               }
            </td>
      </tr>
    }
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3" align="left">Total:</td>
      <td align="left">
        @Model.Cart.ComputeTotalValue().ToString("N2") $
      </td>
    </tr>
  </tfoot>
</table>
<span>
    @using (Html.BeginForm("Catalog", "Caars", FormMethod.Get))
               {
                   <input type="hidden"/>
                  <button  type="submit">Return to shoping</button>
               }
 </span>

</div>
<div>

            <h4 style="color:saddlebrown">Save Order</h4>
            @using (Html.BeginForm("SaveOrder", "Order", FormMethod.Post))
          {/*
            @foreach (var line in Model.Cart.Lines)
            {
             @Model.Order.IdProducts.Add(line.Product.Id)
            }
            
             <input type="hidden" name="IdProducts" value="@Model.Order.IdProducts"/>
         <input type="hidden" name="Created" value="@DateTime.Now()"/>*/
            <p><label asp-for="Order.FirstName" >First Name  </label><br />
            <input type="text" asp-for="Order.FirstName"/>
            <span asp-validation-for="Order.FirstName" />
            </p>
            
            <p><label asp-for="Order.LastName">Last Name</label><br />
           <input type="text"  asp-for="Order.LastName"/>
           <span asp-validation-for="Order.LastName" /></p>
           
           <p>  <label asp-for="Order.Email">Email </label><br />
            <input type="text" asp-for="Order.Email"/>
            <span asp-validation-for="Order.Email" /></p>

            <p>  <label asp-for="Order.Phone">Phone </label><br />
            <input type="text" asp-for="Order.Phone"/>
            <span asp-validation-for="Order.Phone" /></p>
           
          <p> <button type="submit">Create order</button></p>
           }
    </div>